# Question
Look at this function:

```js
const bailOut = () => {
  for (let i = 0; i < 5; i++) {
    if (i > 3) return;
    console.log('Inside the loop', i);
  }
  console.log('Outside the loop');
};
```

Is that `console.log('Outside the loop');` ever going to run? Why or why not?

# Answer
Outside the loop will never run because we use the `return` keyword before we reach that console.log. The `return` keyword will end the function and the loop!


# Teacher Feedback
